### ISSUE TITLE
getLeaves and getChildren throw "Cannot read properties of undefined (reading 'length')"

### ISSUE THREAD

**Issue by 6ichem** [mapbox/supercluster#231]
I'm trying to use getLeaves in the following way:
```
          {clusters &&
            clusters.length > 0 &&
            clusters &&
            clusters?.map((cluster: any) => {
              if (cluster.properties.cluster) {
                console.log(supercluster.getLeaves(cluster.id));

                return (
                  <Cluster
                    key={cluster.properties.cluster_id}
                    lat={cluster.geometry.coordinates[1]}
                    lng={cluster.geometry.coordinates[0]}
                    pointCount={cluster.properties.point_count}
                    onTrigger={() => handleClusterClick(cluster)}
                    hasDeals
                  />
                );
              } else {
                // Render individual markers within the cluster
                const place =
                  markersArray &&
                  markersArray.find(
                    (marker: any) =>
                      marker.properties.id === cluster.properties.id
                  )?.properties;

                return (
                  place && (
                    <MapPin
                      onTrigger={() => triggerRender(place)}
                      place={place}
                      key={place.id}
                      text={place.station_name}
                      lat={place.latitude}
                      lng={place.longitude}
                    />
                  )
                );
              }
            })}
```

I can see the clusters fine on my map but I keep getting this error when trying to get leaves:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Supercluster._getOriginId (index.js?t=1690656057309&v=082d6519:361:41)
    at Supercluster.getChildren (index.js?t=1690656057309&v=082d6519:116:31)
    at Supercluster._appendLeaves (index.js?t=1690656057309&v=082d6519:195:31)
    at Supercluster.getLeaves (index.js?t=1690656057309&v=082d6519:148:14)
    at Map.tsx:374:42
    at Array.map (<anonymous>)
    at SimpleMap (Map.tsx:372:23)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19588:20)
    at beginWork (react-dom.development.js:21601:16)
```

The error reffers ``this.points`` on this function:
```
    // get index of the point from which the cluster originated
    _getOriginId(clusterId) {
        return (clusterId - this.points.length) >> 5;
    }

```

**Comment by 6ichem** [comment]
Fixed, the solution was to initiate Supercluster in the component's state in the following way:
```
  const [supercluster, setsupercluster] = useState(
    new Supercluster({
      radius: 130,
      maxZoom: 10,
      map: (props) => ({ sum: props.myValue }),
    })
  );

```
